--// Systems created @b_aiIeyy (b.ailey.)

--------------------------------------------------------------------------------------------------------------------------------
--- SCRIPTS CREATED FOR THE USE OF BRAMPTON PRIMARY SCHOOL ONLY, THEY MUST NOT BE DISTRIBUTED EXTERNALLY TO ANY OTHER SOURCE ---
--------------------------------------------------------------------------------------------------------------------------------

while true do
	print("hi")
	task.wait(0.5)
end
